[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "prediccion-trafico-zmg"
version = "0.1.0"
description = "Prediccion espacio-temporal de trafico en la ZMG con ST-GNN"
dependencies = [
    "osmnx",
    "networkx",
    "geopandas",
    "shapely",
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "folium"
]

[tool.setuptools.packages.find]
where = ["."]